### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by mtk-i** [SuavePirate/Xamarin.Forms.BottomNavigationTabbedPage#1]
I didn't get it work, I got this weird appearance
![Android](https://user-images.githubusercontent.com/25420453/29032880-c5bc5d66-7b9b-11e7-970b-edd50d521d3f.png)
When I press one of those buttons the app crash, So is this an issue or this library is incomplete stuff?
Thanks in advance.

**Comment by SuavePirate** [comment]
This is still a work in progress.
